def make_txt_file_into_format():
# this will take the .txt file and turn it into rich text that can then be sent as an email
   pass


def get_data_from_supabase():
 #this will get the emails from supabase
 pass
 

def send_emails():
    #this will send emails from the list of emails generated by the function above
    pass